
version: 2

sources:
  - name: main_data
    database: demo_dbt
    schema: public
    tables:
      - name: raw_orders
      - name: raw_payments
      - name: raw_customers

models:
  - name: stg_orders
    description: "Staging fase of the orders of jaffle shop"
  - name: stg_payments
    description: "Staging fase of the payments of jaffle shop"
  - name: stg_customers
    description: "Staging fase of the customers of jaffle shop"

  